import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import React from 'react';
import ThemeWrapper from '@/components/ui/ThemeWrapper';
import Header from '@/components/ui/Header';
import Sidebar from '@/components/ui/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeWrapper>
          <Header />
          <div className="flex">
            <Sidebar />
            <main className="w-full">{children}</main>
          </div>
        </ThemeWrapper>
      </body>
    </html>
  );
}
