import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import React from "react";
import ThemeWrapper from "@/components/UI/ThemeWrapper";
import Sidebar from "@/components/UI/Sidebar";
import Header from "@/components/UI/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeWrapper>
          <Sidebar />
          <Header />
          {children}
        </ThemeWrapper>
      </body>
    </html>
  );
}
