import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import React from 'react';
import ThemeWrapper from '@/components/ui/ThemeWrapper';
import Header from '@/components/ui/Header';
import classNames from 'classnames';
import ModalRenderer from '@/components/modals/ModalRenderer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(inter.className, 'flex min-h-screen flex-col')}
      >
        <ThemeWrapper>
          <ModalRenderer />
          <Header />
          {children}
        </ThemeWrapper>
      </body>
    </html>
  );
}
